---
abstract: 'class builder for hierarchical objects'
author:
  - 'Mike Würfel <sknpp@cpan.org>'
build_requires:
  Test::AbstractMethod: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HO-class
provides:
  HO::abstract:
    file: lib/HO/abstract.pm
    version: '0.02'
  HO::accessor:
    file: lib/HO/accessor.pm
    version: '0.053'
  HO::class:
    file: lib/HO/class.pm
    version: '0.079'
  HO::mixin:
    file: lib/HO/mixin.pm
    version: '0.02'
requires:
  Class::ISA: '0.20'
  Package::Subroutine: '0.022'
  perl: v5.6.0
resources:
  homepage: https://github.com/p5-ho-develop/class/tree/master
  repository: git://github.com/p5-ho-develop/class.git
version: '0.079'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
