---
abstract: 'class builder for hierarchical objects'
author:
  - 'Sebastian Knapp <rock@ccls-online.de>'
build_requires:
  Test::AbstractMethod: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HO-class
requires:
  Class::ISA: '0.20'
  Package::Subroutine: '0.022000'
  perl: v5.6.0
resources:
  homepage: http://github.com/giftnuss/p5-ho-class/tree/master
  repository: git://github.com/giftnuss/p5-ho-class.git
version: '0.074'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
